default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: mangosteen_dev
  username: mangosteen
  password: 123456
  host: db-for-mangosteen

development:
  <<: *default

test:
  <<: *default
  database: mangosteen_1_test
production:
  <<: *default
  database: mangosteen_1_production
  username: mangosteen_1
  password: <%= ENV["MANGOSTEEN_1_DATABASE_PASSWORD"] %>
